sudo: false
cache:
  directories:
  - $PWD/vendor
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
env:
  - COMPOSER_ROOT_VERSION=dev-master
install:
  - composer install --prefer-dist
  - composer require satooshi/php-coveralls:~0.6@stable
script:
  - bin/spectre spec
after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
