sudo: false
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
install:
  - COMPOSER_ROOT_VERSION=dev-master composer update --prefer-dist
script:
  - bin/spectre spec
notifications:
  email: false
