sudo: false
dist: trusty
language: php
php:
  - 5.6
  - 7
  - 7.4
  - hhvm-3.18
install:
  - COMPOSER_ROOT_VERSION=dev-master composer update --prefer-dist
script:
  - bin/spectre spec
notifications:
  email: false
